### ISSUE TITLE
我好像使用不了...

### ISSUE THREAD

**Issue by imnotyangjiu** [friendlyhj/ModFileReader#1]
友谊大佬，我在照你的教程打开 PowerShell 窗口并输入后显示：
java : 无法将“java”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确
，然后再试一次。
所在位置 行:1 字符: 1
+ java -jar .\ModFileReader-1.2-all.jar
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (java:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
我该怎么办？

**Comment by friendlyhj** [comment]
居然有玩 mc 的人没装 java 吗……如果你其实安装过了，把 java 的安装目录添加进 Path 环境变量里去。
